# Generated by Django 3.1.3 on 2020-12-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(default='admin added', max_length=100),
            preserve_default=False,
        ),
    ]
