# Generated by Django 3.1.3 on 2020-12-08 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
