# Generated by Django 3.1.3 on 2020-12-09 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20201209_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
